services:
  - type: web
    name: aiims-portal
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URL
        fromSecret: MONGO_URL
      - key: JWT_SECRET
        fromSecret: JWT_SECRET
      - key: JWT_EXPIRE
        value: 7d